# Generated by Django 6.0.2 on 2026-03-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='designs/')),
                ('category', models.CharField(max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
