# Generated by Django 6.0.2 on 2026-03-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='is_banner',
            field=models.BooleanField(default=False),
        ),
    ]
